language: python
python:
  - "3.9"

addons:
  chrome: stable

branches:
  only:
    - main

gitinstall:
  - pip install pipenv
  - pipenv install --dev

before_script:
   install-webdrivers --path /usr/local/bin/

env:
  global:
    - DJANGO_SETTINGS_MODULE="P8_pur_beurre.settings.travis"

services:
  - postgresql

script:
  - python manage.py test